title: "Jaqueline Lopes — Nail Designer"
description: "Fibra de vidro e blindagem. JJD Studio Beauty."
url: "https://leothaylor.github.io"   # domínio da sua conta
baseurl: "/jaque-nails"               # nome do repositório

# ⚠️ REMOVA qualquer linha "theme: jekyll-theme-primer"
remote_theme: raviriley/agency-jekyll-theme

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Caminhos de imagens usados pelo tema
masthead:
  background: assets/img/header-bg.jpg  # mantenha este arquivo neste caminho

# Opções gerais
markdown: kramdown
highlighter: rouge
