title: "Jaqueline Lopes — Nail Designer"
url: "https://leothaylor.github.io"
baseurl: "/jaque-nails"      # <- MUITO IMPORTANTE
locale: "pt-BR"

theme: jekyll-theme-primer

# Plugins padrão do Pages (não mude)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Caso o tema/partials usem esses dados
description: "Especialista em Fibra de Vidro e blindagem. JJD Studio Beauty."
