title: "Jaqueline Lopes — Nail Designer"
email: ""
description: "Especialista em Fibra de Vidro e Blindagem"
lang: "pt-BR"

url: "https://leothaylor.github.io"
baseurl: "/jaque-nails"   # <- MUITO IMPORTANTE

# Tema Agency
remote_theme: raviriley/agency-jekyll-theme@v2.2.0

# Plugins suportados no GitHub Pages
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
